#!/bin/bash
amixer -c 0 get Side,3 | grep off > /dev/null; if [ $? = 1 ]; then amixer -q -c 0 set Side,3 mute; else amixer -q -c 0 set Side,3 unmute; fi;
amixer -c 0 get Master,0 | grep off > /dev/null; if [ $? = 1 ]; then amixer -q -c 0 set Master,0 mute; else amixer -q -c 0 set Master,0 unmute; fi;
